# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenapiChanges < Formula
  desc "The worlds fastest and most scalable OpenAPI linter"
  homepage "https://quobix.com/vacuum"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.2/openapi-changes_0.0.2_darwin_x86_64.tar.gz"
      sha256 "ed39ce336ffafd88548a3a45cc16db025297e2fc5676af2657dc11ce6efbfe04"

      def install
        bin.install "vacuum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.2/openapi-changes_0.0.2_darwin_arm64.tar.gz"
      sha256 "07a5ae04f65e4d6458ec02b343cc926f587df26adbd6c6e5761335147c06ec8b"

      def install
        bin.install "vacuum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.2/openapi-changes_0.0.2_linux_arm64.tar.gz"
      sha256 "a86ddc67d4542e300040767112ee9b711a567355cbf3c77a7db238d9b304ea79"

      def install
        bin.install "vacuum"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.2/openapi-changes_0.0.2_linux_x86_64.tar.gz"
      sha256 "193fc7e473251f1c25dc1d6d642adcd2f93e28e26130cef22bda437aa963b941"

      def install
        bin.install "vacuum"
      end
    end
  end
end
