# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vacuum < Formula
  desc "The worlds fastest and most scalable OpenAPI linter"
  homepage "https://quobix.com/vacuum"
  version "0.3.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/daveshanley/vacuum/releases/download/v0.3.4/vacuum_0.3.4_darwin_arm64.tar.gz"
      sha256 "5b803ac63e380f1198fb9b1057ddac82cb4035b0375b1816095136373719a6e2"

      def install
        bin.install "vacuum"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/daveshanley/vacuum/releases/download/v0.3.4/vacuum_0.3.4_darwin_x86_64.tar.gz"
      sha256 "473707c8f236b51b93d7adca9d1070ee9349362a8be7c327a4509c9c464661a2"

      def install
        bin.install "vacuum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daveshanley/vacuum/releases/download/v0.3.4/vacuum_0.3.4_linux_arm64.tar.gz"
      sha256 "27fb84a5ff5c541f6426f90ef2fe9cbbcd6c56ac1fae090ebb75aaf64743e8a8"

      def install
        bin.install "vacuum"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/daveshanley/vacuum/releases/download/v0.3.4/vacuum_0.3.4_linux_x86_64.tar.gz"
      sha256 "afd932b75530fb283d5f58129675690001bbfaeaf819c46f2ca4fa65a742b035"

      def install
        bin.install "vacuum"
      end
    end
  end
end
