# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vacuum < Formula
  desc "The worlds fastest and most scalable OpenAPI linter"
  homepage "https://quobix.com/vacuum"
  version "0.17.11"

  on_macos do
    on_intel do
      url "https://github.com/daveshanley/vacuum/releases/download/v0.17.11/vacuum_0.17.11_darwin_x86_64.tar.gz"
      sha256 "f9f67669c4add011ec3b7319fb7d9222fd7071bca5e10f401bbbd157294588ce"

      def install
        bin.install "vacuum"
      end
    end
    on_arm do
      url "https://github.com/daveshanley/vacuum/releases/download/v0.17.11/vacuum_0.17.11_darwin_arm64.tar.gz"
      sha256 "e5fdc039486c98b8d603c6daa35dfa911562fc3dc2aff503a8aa736cc235cbfe"

      def install
        bin.install "vacuum"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/daveshanley/vacuum/releases/download/v0.17.11/vacuum_0.17.11_linux_x86_64.tar.gz"
        sha256 "d80aa398d64500723bcc339845a295f447d89fe2da3df85ff66e4dc6564cbf1c"

        def install
          bin.install "vacuum"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/daveshanley/vacuum/releases/download/v0.17.11/vacuum_0.17.11_linux_arm64.tar.gz"
        sha256 "acd8f56eb581192f1c447ef2639ce64efbdad19f40dfd0a361f54b824ffcc892"

        def install
          bin.install "vacuum"
        end
      end
    end
  end
end
