# This file was generated by GoReleaser. DO NOT EDIT.
cask "vacuum" do
  version "0.26.0"

  on_macos do
    on_intel do
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_darwin_x86_64.tar.gz"
      sha256 "f5618d20dcdb47e8dd8aa43e4abaa1cf5bba4f1b5cbd13e384f59cd1247fab7f"
    end
    on_arm do
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_darwin_arm64.tar.gz"
      sha256 "7fdad92a67137af1a809be812137036af2a8c859fa2e08be8949a29ca47c8007"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_linux_x86_64.tar.gz"
      sha256 "04e1b648096cc9fddab878fe03f1d2761c677afe5bb7e24b9814e6c28aa5b855"
    end
    on_arm do
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_linux_arm64.tar.gz"
      sha256 "3f6c2c4386e594fd8f2ea407639943fca48a23aa298dd70dd29e81840eb1e800"
    end
  end

  name "vacuum"
  desc "The worlds fastest and most scalable OpenAPI linter"
  homepage "https://quobix.com/vacuum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vacuum"

  # No zap stanza required

end
