# This file was generated by GoReleaser. DO NOT EDIT.
cask "vacuum" do
  version "0.29.5"

  on_macos do
    on_intel do
      sha256 "68b5e045a2e95952a175393ce9e8292d14f0196a6aa0d991233848c9710c55f3"
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d20996d535f7e744fc5886a9f05e8ad391a97040f18406d107578d3f3319c075"
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0fa517cee190793ee97d15b785ccebfa5b96096c64a3b549f5336b010bc01232"
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "119e141ca5a1742f5a99a6bb3c48711aae714e0add2285b1fc1888541a26b56b"
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vacuum"
  desc "The worlds fastest and most scalable OpenAPI linter"
  homepage "https://quobix.com/vacuum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vacuum"

  # No zap stanza required

end
