# This file was generated by GoReleaser. DO NOT EDIT.
cask "vacuum" do
  version "0.30.4"

  on_macos do
    on_arm do
      sha256 "f1cc321c6cdb8c4c19aeb4bf92600be8cc30cbd4fc0c4e0489f241c5c14e8c75"
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cbb57005363f248aa85c4c9e4d64e2fbbc7a05c1faf54c056083adc9e2e476c2"
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "33eb0320a177512974b5b009ccd851803b38d434fd54fe703c83445036be114f"
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aafa08e9fc349fd6051529ec937b31f25d138951a609fda27c17b7fc8bd3520f"
      url "https://github.com/daveshanley/vacuum/releases/download/v#{version}/vacuum_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "vacuum"
  desc "The worlds fastest and most scalable OpenAPI linter"
  homepage "https://quobix.com/vacuum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vacuum"

  # No zap stanza required
end
